### ISSUE TITLE
ERROR : uninitialized constant StatsController

### ISSUE THREAD

**Issue by mauriziotallarico** [myaspm/redmine_stats_2#3]
Error log

        /usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5.2/lib/active_support/inflector/methods.rb:261:in `const_get'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5.2/lib/active_support/inflector/methods.rb:261:in `block in constantize'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5.2/lib/active_support/inflector/methods.rb:259:in `each'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5.2/lib/active_support/inflector/methods.rb:259:in `inject'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5.2/lib/active_support/inflector/methods.rb:259:in `constantize'
/usr/local/rvm/gems/ruby-2.1.0/gems/actionpack-4.2.5.2/lib/action_dispatch/routing/route_set.rb:70:in `controller_reference'
/usr/local/rvm/gems/ruby-2.1.0/gems/actionpack-4.2.5.2/lib/action_dispatch/routing/route_set.rb:60:in `controller'
/usr/local/rvm/gems/ruby-2.1.0/gems/actionpack-4.2.5.2/lib/action_dispatch/routing/route_set.rb:39:in `serve'
/usr/local/rvm/gems/ruby-2.1.0/gems/actionpack-4.2.5.2/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/usr/local/rvm/gems/ruby-2.1.0/gems/actionpack-4.2.5.2/lib/action_dispatch/journey/router.rb:30:in `each'
/usr/local/rvm/gems/ruby-2.1.0/gems/actionpack-4.2.5.2/lib/action_dispatch/journey/router.rb:30:in `serve'
/usr/local/rvm/gems/ruby-2.1.0/gems/actionpack-4.2.5.2/lib/action_dispatch/routing/route_set.rb:815:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/rack-raw-upload-1.1.1/lib/rack/raw_upload.rb:18:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/actionpack-xml_parser-1.0.2/lib/action_dispatch/xml_params_parser.rb:16:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/var/www/redmine/plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/flash.rb:260:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
/usr/local/rvm/gems/ruby-2.1.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5.2/lib/active_record/query_cache.rb:36:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.1.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/railties-4.2.5.2/lib/rails/rack/logger.rb:38:in `call_app'
/usr/local/rvm/gems/ruby-2.1.0/gems/railties-4.2.5.2/lib/rails/rack/logger.rb:20:in `block in call'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5.2/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5.2/lib/active_support/tagged_logging.rb:26:in `tagged'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5.2/lib/active_support/tagged_logging.rb:68:in `tagged'
/usr/local/rvm/gems/ruby-2.1.0/gems/railties-4.2.5.2/lib/rails/rack/logger.rb:20:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5.2/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/static.rb:116:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/railties-4.2.5.2/lib/rails/engine.rb:518:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/railties-4.2.5.2/lib/rails/application.rb:165:in `call'
/usr/local/rvm/gems/ruby-2.1.0/gems/railties-4.2.5.2/lib/rails/railtie.rb:194:in `public_send'
/usr/local/rvm/gems/ruby-2.1.0/gems/railties-4.2.5.2/lib/rails/railtie.rb:194:in `method_missing'
/usr/local/rvm/gems/ruby-2.1.0/gems/passenger-5.0.5/lib/phusion_passenger/rack/thread_handler_extension.rb:85:in `process_request'
/usr/local/rvm/gems/ruby-2.1.0/gems/passenger-5.0.5/lib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
/usr/local/rvm/gems/ruby-2.1.0/gems/passenger-5.0.5/lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/usr/local/rvm/gems/ruby-2.1.0/gems/passenger-5.0.5/lib/phusion_passenger/request_handler.rb:414:in `block (3 levels) in start_threads'
/usr/local/rvm/gems/ruby-2.1.0/gems/passenger-5.0.5/lib/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'

**Comment by myaspm** [comment]
Can't reproduce this, how did you get the error?

**Comment by mauriziotallarico** [comment]
Hello , using Centos, Redmine 3.2.1 with mysql, some sort of link for "stats" exists only in the admin page and when i click on this link i get the above mentioned error. Maybe some interaction with some other plugin ?

**Comment by myaspm** [comment]
redmine_dmsf is giving some error i guess let me check it.

Edit : Hey man, i've tested with Redmine 3.2.1 latest DMSF plugin and this plugin on mysql but couldnt find a problem. There must be a Statistics link at the top menu, can you try accessing from there or can you give me a screenshot of the place where you get the problem?

**Comment by mauriziotallarico** [comment]
Hello, no link "Statistics" on "normal" user account (snap1.jpg).
The only change is the link "translation_missing" etc. on the admin page (snap2.jpg)

Thanks !

![snap1](https://cloud.githubusercontent.com/assets/19352879/20492390/dd0e7d9e-b014-11e6-9f86-2b658144aae6.JPG)
![snap2](https://cloud.githubusercontent.com/assets/19352879/20492389/dd0e03a0-b014-11e6-87e4-3e2d680616fb.JPG)

**Comment by myaspm** [comment]
For Statistics to be ssen on a normal User login, you need to give permissions from Roles and permissions menu on admin page.

In Administration -> Roles And Permission page under the Project tab, there will be a option "Access Statistics".

**Comment by mauriziotallarico** [comment]
Hello , i've done this thanks . Now i can see that link also on normal user page.
Still the error remains ... .

**Comment by myaspm** [comment]
Can you give me a complete list of your plugins? Preferably a full screenshot from Administration -> Information page.

**Comment by mauriziotallarico** [comment]
sure: other 2 snapshots
![snap3](https://cloud.githubusercontent.com/assets/19352879/20593037/0e7fc4d2-b231-11e6-95cb-47c39188e21b.JPG)
![snap4](https://cloud.githubusercontent.com/assets/19352879/20593036/0e794c6a-b231-11e6-8b10-5e8d2cb4a6c1.JPG)

**Comment by mauriziotallarico** [comment]
I think it could be actually DMSF as you supposed initially :

Started GET "/global_stats/current_week" for XXX.XXX.XXX.XXX at 2016-11-24 10:13:54 +0100

ActionController::RoutingError (uninitialized constant StatsController):

  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'


Processing by UsErrorsController#error_404 as HTML
  Parameters: {"time_filter"=>"current_week"}
  Current user: dummy (id=6)
  Rendered plugins/usability/app/views/errors/error_status.html.erb (5.9ms)
Completed 404 Not Found in 82ms (Views: 5.9ms | ActiveRecord: 71.2ms)

**Comment by myaspm** [comment]
One final question, did you rename the plugin folder from redmine_stats_2 to redmine_stats?

**Comment by mauriziotallarico** [comment]
I'm really sorry i   didn't read carefully. It works now , thanks a lot and sorry again !

**Comment by myaspm** [comment]
No problem glad it works now.
