### ISSUE TITLE
the language can not change after you change one time

### ISSUE THREAD

**Issue by candy-Joke** [myaspm/redmine_stats_2#7]
after I change my page from english to chinese, the name:statistics change to chinese, but when i change it back to english,  unless i restart the redmine service,  it will keep the prior language

**Comment by myaspm** [comment]
Sorry i was busy, is the problem solved? If so, how did you do it?

**Comment by candy-Joke** [comment]
no, the problem persist, for temporary action, I restart the redmine service, and it back to normal
I used is as a administrator function, now allow someone change the language





At 2017-01-09 15:05:04, "Mustafa Yılmaz" <notifications@github.com> wrote:


Sorry i was busy, is the problem solved? If so, how did you do it?

**Comment by matletix** [comment]
I got correct traduction in French, but when I change to English or another language, the plugin displays in Russian, not sure why, may be related to this
